Add HowGay with Updated Features
l-zeuch/lagpdb-cc pull request #46
Opened 2021-08-05 23:48 UTC by mangowhite

![msedge_YWUVE2wviX](https://user-images.githubusercontent.com/75037449/128435334-395eb821-0ddd-4224-9e2b-d5e585d7a79a.png)

**What this PR does and why it should be merged**

• How Gay displays a top.
• How Gay has an 100% Gay Easter-egg.
• How Gay is easy to use.
• How Gay saves the values in the database.

**Status**

* [X] Code has been tested on an official instance of YAGPDB, or there are no code changes
* [X] I've read and understood the [contribution guidelines](../CONTRIBUTING.md)

2021-08-05 23:56 UTC, l-zeuch requested changes
found a few things :')

2021-08-05 23:56 UTC, l-zeuch commented on howgay.go
> +{{$howGay:=randInt 0 101}}
can just be `... randInt 101`

2021-08-05 23:56 UTC, l-zeuch commented on howgay.go
> +/*}}
doesn't match requested format, refer to README

2021-08-05 23:56 UTC, l-zeuch commented on howgay.go
> +{{/*VARIABLES*/}}
```suggestion

```
this might confuse users that there is config, although there is not.

2021-08-05 23:56 UTC, l-zeuch commented on howgay.go
> +{{/*CODE*/}}
move this further up

2021-08-06 00:22 UTC, mangowhite commented on howgay.go
> +{{$howGay:=randInt 0 101}}
Done!

2021-08-06 00:23 UTC, mangowhite commented on howgay.go
> +/*}}
Done!

2021-08-06 00:23 UTC, mangowhite commented on howgay.go
> +{{/*VARIABLES*/}}
Removed!

2021-08-06 00:23 UTC, mangowhite commented
All done!

2021-08-06 00:24 UTC, mangowhite commented on howgay.go
> +{{/*CODE*/}}
Done.

2021-08-06 00:29 UTC, l-zeuch approved these changes

2021-08-06 00:31 UTC, merged